# color = input("Enter a color: ")
# plural_noun = input("Enter a Plural Noun: ")
# celebrity = input("Enter a celebrity: ")

# print("Roses are " + color)
# print(plural_noun + " are blue")
# print("I love " + celebrity)
# print("How about you?")

adjective1 =  input("Enter an adjective: ")
noun1 = input("Enter an noun: ")
plural_noun1 = input("Enter a plural noun: ")
person_in_room_female = input("Enter a name for a female: ")
adjective2 =  input("Enter an adjective: ")
article_of_clothing = input("Enter an article of clothing: ")
noun2 = input("Enter an noun: ")
city = input("Enter the name of a city: ")
plural_noun2 = input("Enter a plural noun: ")
adjective3 =  input("Enter an adjective: ")
part_of_the_body1 = input("Enter a body part: ")
alphabet_letter = input("Enter a letter from the alphabet: ")
celebrity = input("Enter a celebrity: ")
plural_noun3 = input("Enter a plural noun: ")
adjective4 =  input("Enter an adjective: ")
place = input("Enter a place: ")
part_of_the_body2 = input("Enter a body part: ")
adjective5 =  input("Enter an adjective: ")
adjective6 =  input("Enter an adjective: ")
verb = input("Enter a verb: ")
plural_noun4 = input("Enter a plural noun: ")
number = input("Enter a number: ")

print("There are many " + adjective1 + " ways to choose a/an " + noun1 + " to read.")
print("First, you could ask for recommendations from your friends and " + plural_noun1 + ".")
print("Just don't ask Aunt " + person_in_room_female + "-she only reads " + adjective2 + " books with " + article_of_clothing + "-ripping goddesses on the cover.")
print("If your friends and family are no help, try checking out the " + noun2 + " Review in 'The " + city + " Times'.")
print("If the " + plural_noun2 + " featured there are too " + adjective3 + " for your taste, try something a little more low-" + part_of_the_body1 +
", like " + alphabet_letter + ": 'The " + celebrity + " Magazine', or '" + plural_noun3 + " Magazine'.")
print("You could also choose a book the " + adjective4 + "-fashioned way.")
print("Head to your local library or " + place + " and browse the shelves until something catches your " + part_of_the_body2 + ".")
print("Or, you could save yourself a whole lot of " + adjective5 + " trouble and log on to www.bookish.com, the " + adjective6 + " new website to "
+ verb + " for books!")
print("With all the time you'll save not having to search for " + plural_noun4 + ", you can read " + number + " more books!")